### ISSUE TITLE
How to find out if `code` call is finished?

### ISSUE THREAD

**Issue by smehner1** [RobTillaart/HeartBeat#12]
Hi there,

I am working on a low-power Arduino application and want to use the HeartBeat library to indicate (sensing) errors with an LED. To achieve this, I want to wait until the l`ed_ok.code()`function completes before the Arduino goes into deep sleep.

I already tried using `led_ok.isEnabled()`, but this returns false (because I disabled the LED in the setup function). For my understanding, `led_ok.getState()` returns whether the LED is currently on or off.

Could you please provide me with a hint or suggestion on how to achieve this?

Here is a minimal code snippet:

```cpp
#include <ArduinoLowPower.h>
#include "HeartBeat.h"

#define LED_OK_PIN 4

HeartBeatDiag led_ok;

unsigned long now = 0;
bool already_called = false;

void setup() 
{
  Serial.begin(115200);
  while (! Serial);

  led_ok.begin(LED_OK_PIN, 5);
  led_ok.disable();
}


void loop()
{
  led_ok.beat();

  // only do it once 
  if (! already_called) 
  {
    already_called = true;
    Serial.println("start led pattern");
    led_ok.code(9339); 
    now = millis();
  }
  
  // if code method call is done: go into deep sleep
  while(millis() - now < 5000) // TODO
  {
    led_ok.beat();
  }
  
  Serial.println("led pattern done");
  
  LowPower.deepSleep(10000);
  already_called=false;
}
```

In my productive code I am using a state machine and for this reason I want to block the code with the while loop at this point. 

(updates syntax highlight)

**Comment by RobTillaart** [comment]
Thanks for your question. As I am rather busy it might take some time before I can answer your question.
Will be back asap

**Comment by RobTillaart** [comment]
@smehner1 

If I understand your question you need an extra function like

```cpp
bool HeartBeatDiag::codeCompleted()
{
  if (_codeMask > 0) return false;
  return true;
}
```

The above should be in the .cpp file 
The class definition in the .h file should have the public function.

```cpp
bool codeCompleted();
```

Will make a develop branch and PR asap.

(updated)

**Comment by RobTillaart** [comment]
Update: PR is running.

**Comment by RobTillaart** [comment]
Updated HeartBeat_errorcode.ino to use **codeCompleted()**

(to be continued later)

**Comment by smehner1** [comment]
Hi and thank you a lot. 
The code works as expected. 👍

**Comment by RobTillaart** [comment]
Then I will merge and publish in a few minutes.
(done)
